version: '3.5'
services:
  crackerjack:
    build:
      context: .
      args:
        - ADD_WORDLIST_N_RULES=true
    container_name: crackerjack
    image: ghcr.io/yimura/crackerjack-docker:nvidia
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./data/:/opt/crackerjack/data/
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
