name: Build & Push

on:
  push:
    # branches:
    #   - "master"
    # paths:
    #   - "**/Dockerfile"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-dependencies:
    name: Dependencies
    strategy:
      fail-fast: true
      matrix: 
        image: [ wordlists, hashcat ]
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout source
        uses: actions/checkout@v4

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      -
        name: Build dependency
        uses: docker/build-push-action@v5
        with:
          file: ${{ matrix.image }}/Dockerfile
          tags: yimura/crackerjack-docker:${{ matrix.image }}
          build-args: |
            ADD_WORDLIST_N_RULES=true
          outputs: type=docker,dest=/tmp/${{ matrix.image }}.tar
      
      -
        name: Upload dependency
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.image }}
          path: /tmp/${{ matrix.image }}.tar
      
  build-container:
    name: CPU & GPU
    needs: [ build-dependencies ]
    strategy:
      fail-fast: true
      matrix:
        image: [ cpu, nvidia ]
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout source
        uses: actions/checkout@v4

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      -
        name: Download wordlists dependency
        uses: actions/download-artifact@v4
        with:
          name: wordlists
          path: /tmp
      
      -
        name: Load wordlists dependecy
        run: docker load --input /tmp/wordlists.tar

      - 
        name: Free disk space
        run: rm -rf /tmp/*.tar

      -
        name: Download hashcat dependency
        uses: actions/download-artifact@v4
        with:
          name: hashcat
          path: /tmp
      
      -
        name: Load hashcat dependecy
        run: docker load --input /tmp/hashcat.tar

      - 
        name: Free disk space
        run: rm -rf /tmp/*.tar

      -
        name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: yimura
          password: ${{ secrets.PACKAGE_WRITE_TOKEN }}

      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: yimura
          password: ${{ secrets.DOCKER_TOKEN }}

      -
        name: Build and push to Docker Hub
        uses: docker/build-push-action@v4
        with:
          file: ${{ matrix.image }}/Dockerfile
          push: true
          tags: yimura/crackerjack-docker:${{ matrix.image }}

      -
        name: Retag and push to Github Container Registry
        run: |
          docker buildx imagetools create --tag ghcr.io/yimura/crackerjack-docker:${{ matrix.image }} yimura/crackerjack-docker:${{ matrix.image }}
